add choose

diff --git a/executable/IPUconda b/executable/IPUconda
--- a/executable/IPUconda
+++ b/executable/IPUconda
@@ -1,19 +1,60 @@
 #!/bin/bash
 
-export POP_DIR_BASE="/mnt/scratch001/custeng-cn-scratch/yongxiy"
+EXECUTABLE_CACHE_PATH="${HOME}/.cache"
+
+if [[ -z ${TMPDIR} ]]; then
+  TMPDIR="/tmp"
+fi
+
+IPUOF_CONFIG_PATH="${POP_BASE_DIR}/sdk/pod16_ipuof.conf"
+
+function _input() {
+  echo "${1}"
+  if [[ $# -eq 2 ]]; then
+    echo -ne "[default: ${2}] >> "
+  else
+    echo -ne ">> "
+  fi
+  read _INPUTS
+}
+
+function check_file_exist()
+{
+  _file=$1
+  if [ ! -f $_file ];then
+    printf "%s is not file or file does not exist\n" $_file
+    exit 1
+  fi	
+}
+
+function _input_config_env(){
+  _input "please enter executable graph cache path (absolute path):" ${EXECUTABLE_CACHE_PATH}
+  EXECUTABLE_CACHE_PATH=${_INPUTS:-${EXECUTABLE_CACHE_PATH}}
+  if [ ! -d ${EXECUTABLE_CACHE_PATH} ];then
+    mkdir -p ${EXECUTABLE_CACHE_PATH}
+  fi
+  
+  _input "please enter tempary variables stored path (absolute path):" ${TMPDIR}
+  TMPDIR=${_INPUTS:-${TMPDIR}}
+  if [ ! -d ${TMPDIR} ];then
+    mkdir -p ${TMPDIR}
+  fi
+
+  _input "please enter tempary variables stored path (absolute path):" ${IPUOF_CONFIG_PATH}
+  IPUOF_CONFIG_PATH=${_INPUTS:-${IPUOF_CONFIG_PATH}}
+  check_file_exist ${IPUOF_CONFIG_PATH}
+}
 
 function _create_conda_activate_script(){
   local file_path=$1
   cat <<EOF > "${file_path}"
 #!/bin/bash
 # set -ex
-
 export GCDA_MONITOR=1
 export TF_CPP_VMODULE="poplar_compiler=1,poplar_executable=1"
-export TF_POPLAR_FLAGS="--max_compilation_threads=40 --executable_cache_path=/mnt/scratch001/custeng-cn-scratch/yongxiy/cachedir --show_progress_bar=true"
-export TMPDIR="/mnt/scratch001/custeng-cn-scratch/yongxiy/tmp"
-export IPUOF_CONFIG_PATH="/localdata/yongxiy/env/ipu-config/pod64/\$HOST/ipuof.conf"
-
+export TF_POPLAR_FLAGS="--max_compilation_threads=40 --executable_cache_path=${EXECUTABLE_CACHE_PATH} --show_progress_bar=true"
+export TMPDIR="$TMPDIR"
+export IPUOF_CONFIG_PATH="$IPUOF_CONFIG_PATH"
 export _OLD_TMPDIR=\$TMPDIR
 export _OLD_CMAKE_PREFIX_PATH=\$CMAKE_PREFIX_PATH
 export _OLD_PATH=\${PATH#\$CONDA_PREFIX/bin:}
@@ -23,8 +64,6 @@ export _OLD_LD_LIBRARY_PATH=\$LD_LIBRARY_PATH
 export _OLD_OMPI_CPPFLAGS=\$OMPI_CPPFLAGS
 export _OLD_OPAL_PREFIX=\$OPAL_PREFIX
 export _OLD_PYTHONPATH=\$PYTHONPATH
-
-
 function check_file_exist()
 {
   _file=\$1
@@ -32,17 +71,14 @@ function check_file_exist()
     printf "\e[93m%s is not file or file does not exist\n\e[0m" \$_file
   fi	
 }
-
-check_file_exist "$POP_DIR_BASE/sdk/poplar_sdk-ubuntu_18_04-2.0.0+481-79b41f85d1/popart-ubuntu_18_04-2.0.0+108156-165bbd8a64/enable.sh"
-pushd $POP_DIR_BASE/sdk/poplar_sdk-ubuntu_18_04-2.0.0+481-79b41f85d1/popart-ubuntu_18_04-2.0.0+108156-165bbd8a64
-  source "$POP_DIR_BASE/sdk/poplar_sdk-ubuntu_18_04-2.0.0+481-79b41f85d1/popart-ubuntu_18_04-2.0.0+108156-165bbd8a64/enable.sh"
+check_file_exist "$POP_DIR/popart-ubuntu_18_04-2.0.0+108156-165bbd8a64/enable.sh"
+pushd $POP_DIR/popart-ubuntu_18_04-2.0.0+108156-165bbd8a64
+  source "$POP_DIR/popart-ubuntu_18_04-2.0.0+108156-165bbd8a64/enable.sh"
 popd
-
-check_file_exist "$POP_DIR_BASE/sdk/poplar_sdk-ubuntu_18_04-2.0.0+481-79b41f85d1/poplar-ubuntu_18_04-2.0.0+108156-165bbd8a64/enable.sh"
-pushd $POP_DIR_BASE/sdk/poplar_sdk-ubuntu_18_04-2.0.0+481-79b41f85d1/poplar-ubuntu_18_04-2.0.0+108156-165bbd8a64
-  source "$POP_DIR_BASE/sdk/poplar_sdk-ubuntu_18_04-2.0.0+481-79b41f85d1/poplar-ubuntu_18_04-2.0.0+108156-165bbd8a64/enable.sh"
+check_file_exist "$POP_DIR/poplar-ubuntu_18_04-2.0.0+108156-165bbd8a64/enable.sh"
+pushd $POP_DIR/poplar-ubuntu_18_04-2.0.0+108156-165bbd8a64
+  source "$POP_DIR/poplar-ubuntu_18_04-2.0.0+108156-165bbd8a64/enable.sh"
 popd
-
 # set +ex
 EOF
 }
@@ -52,7 +88,6 @@ function _create_conda_deactivate_script(){
   cat <<EOF > "${file_path}"
 #!/bin/bash
 # set -ex
-
 export TMPDIR=\$_OLD_TMPDIR
 export CMAKE_PREFIX_PATH=\$_OLD_CMAKE_PREFIX_PATH
 export PATH=\$_OLD_PATH
@@ -62,7 +97,6 @@ export LD_LIBRARY_PATH=\$_OLD_LD_LIBRARY_PATH
 export OMPI_CPPFLAGS=\$_OLD_OMPI_CPPFLAGS
 export OPAL_PREFIX=\$_OLD_OPAL_PREFIX
 export PYTHONPATH=\$_OLD_PYTHONPATH
-
 unset GCDA_MONITOR
 unset TF_CPP_VMODULE
 unset TF_POPLAR_FLAGS
@@ -101,6 +135,8 @@ function conda_wrapper_help_msg(){
   echo "    -h, --help: print helpful message"
 }
 
+POP_DIR_BASE="/mnt/scratch001/custeng-cn-scratch/yongxiy"
+POP_DIR="${POP_DIR_BASE}/sdk/poplar_sdk-ubuntu_18_04-2.0.0+481-79b41f85d1"
 
 function extract_condaenv_name(){
     local conda_str=$1
@@ -138,6 +174,51 @@ fi
 _CONDA_CMD=$@
 echo "${_CONDA_CMD}"
 extract_condaenv_name ${_CONDA_CMD}
+
+POP_DIR_BASE="/mnt/scratch001/custeng-cn-scratch/yongxiy"
+
+echo "please input sdk base directory:"
+echo -ne "[default $POP_DIR_BASE (abslute path)] >> "
+read POP_DIR_BASE_
+
+if [[ ! -z $POP_DIR_BASE_ ]]; then
+  POP_DIR_BASE=$POP_DIR_BASE_
+fi 
+
+POP_DIR="${POP_DIR_BASE}/sdk"
+
+cd "${POP_DIR_BASE}/sdk"
+prompt="Please select a SDK version:"
+options=( $(find -maxdepth 1 -name 'poplar_sdk*' -type d -printf '%P ' | xargs -0) )
+
+PS3="$prompt "
+select opt in "${options[@]}" "Quit" ; do 
+    if (( REPLY == 1 + ${#options[@]} )) ; then
+        exit
+
+    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
+        echo  "poplar sdk: $opt"
+        POP_DIR="${POP_DIR}/$opt"
+        break
+    else
+        echo "Invalid option. Try another one."
+    fi
+done
+cd -
+
+POPART_BASE=$(find $POP_DIR -maxdepth 1 -name "popart-*")
+POPLAR_BASE=$(find $POP_DIR -maxdepth 1 -name "poplar-*")
+
+_input_config_env
+
+
+# POPART_BASE="${POP_DIR}/${_POPART_}"
+# POPLAR_BASE="${POP_DIR}/${_POPLAR_}"
+
+# echo $POP_DIR
+# echo $POPART_BASE
+# echo $POPLAR_BASE
+
 bash -ic "${_CONDA_CMD}"
 
 _CONDA_ENV_DEFAULT_PREFIX="$(dirname $(dirname $(which conda)))/envs"
@@ -158,4 +239,4 @@ if [[ $? != 0 ]]; then
     exit 0
 fi
 
-unset POP_DIR_BASE
+# unset POP_DIR_BASE
